title: Sorting Algorithms Visualizer
description: A site offering interactive simulations of different sorting algorithms, helping users understand how they work visually without relying on lengthy theoretical explanations.
theme: minima
